


service: product-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          path: products
          method: get
  getProductsById:
    handler: handler.getProductsById
    package:
      include:
        - "./data.json"
    events:
      - http:
          path: products/{productId}
          method: get
